### ISSUE TITLE
PHP Parse error

### ISSUE THREAD

**Issue by TomFrearson** [OddOneOut/bwp-recaptcha#18]
I just updated to version 2.0.0 and it triggered a fatal error:

`PHP Parse error:  syntax error, unexpected '[' in /var/www/html/wp-content/plugins/bwp-recaptcha/includes/provider/abstract-provider.php on line 131`

I've commented out the line for now and the plugin is working.

Hope that helps,
Tom

**Comment by kminh** [comment]
What version of PHP are you using?

**Comment by TomFrearson** [comment]
PHP version: 5.3.29

Thanks for the quick fix!
