### ISSUE TITLE
Impossible to submit CF7 form with BWP reCaptcha 2.0.1

### ISSUE THREAD

**Issue by dregad** [OddOneOut/bwp-recaptcha#21]
Greetings,

I recently upgraded to 2.0.1 (from whatever 1.x version I was running before). 

Yesterday I published a new article, integrating a *Contact Form 7* form which I have successfully used in the past without any issues. 

Users reported being unable to submit the form. After completing the captcha and clicking the submit button, it just spins endlessly. I can confirm this behavior too, on several distinct client platforms. After unckecking *Integrate with Contact Form 7* in general options, the form can be submitted.

I am running WP 4.3.1, CF7 4.3 and BWP reCaptcha 2.0.1.

**Comment by dregad** [comment]
For the benefit of other users who may be facing the same issue, I realized after a bit of research that [CF7 4.3 natively integrates recaptcha](http://contactform7.com/2015/09/17/contact-form-7-43/).

So the easy solution for me was to configure CF7 with my recaptcha API keys, disable BWP integration and update the form to use the CF7 syntax for the recaptcha tag (basically adding `id:`in front of the tag name).

**Comment by kminh** [comment]
I will see if there's a way to override CF7's recaptcha tag when the integration is enabled. So users can switch easily between the builtin one or the one provided by BWP recaptcha.

**Comment by dregad** [comment]
OK, thanks for your feedback

**Comment by kminh** [comment]
@dregad are you available to test version 2.0.2 ?

Actually I wasn't able to reproduce this issue as BWP recaptcha overrides the default implementation correctly. If possible, please:

1. Post an example form here
2. Post the ajax response you got from the server when you see the endless spinning icon. Also, please check if there's any javascript error in the console.

Thanks.

**Comment by dregad** [comment]
Hey,

Sorry I can't upgrade the live blog right now, and unfortunately don't have time to setup a test environment either. 

Here's what I get with 2.0.1, hopefully that helps

- Sample form
    ```
[text* nom akismet:author] 
[recaptcha inscr-recaptcha]
[submit "Envoyer"]
```

- Server response
    ```
<br />
<b>Warning</b>:  file_get_contents(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 in <b>/.../wordpress/wp-content/plugins/bwp-recaptcha/vendor/google/recaptcha/src/ReCaptcha/RequestMethod/Post.php</b> on line <b>68</b><br />
<br />
<b>Warning</b>:  file_get_contents(https://www.google.com/recaptcha/api/siteverify): failed to open stream: no suitable wrapper could be found in <b>/.../wordpress/wp-content/plugins/bwp-recaptcha/vendor/google/recaptcha/src/ReCaptcha/RequestMethod/Post.php</b> on line <b>68</b><br />
{"mailSent":false,"into":"#wpcf7-f967-p968-o1","captcha":null,"message":"Erreur de validation. Veuillez v\u00e9rifier les champs et soumettre \u00e0 nouveau.","invalids":[{"into":"span.wpcf7-form-control-wrap.inscr-recaptcha","message":"Unknown error. Please contact an administrator for more info.","idref":null}],"onSubmit":["if (grecaptcha) { grecaptcha.reset(bwpRecaptchaWidget1); }"]}
```

**Comment by kminh** [comment]
I see, so that was indeed a different issue, which has been fixed in 2.0.2. So after upgrading to 2.0.2 you should be able to simply turn the integration back on if you want features provided by BWP recaptcha.

Thanks for all the info.

**Comment by dregad** [comment]
OK, many thanks for your feedback.
As a side note, just realized that 2.0.2. is not (yet?) available on wp.org site - should I download it from the git repo ? Are you planning to release it soon ?

**Comment by kminh** [comment]
Just pushed 2.0.2 to github, but to use it you will need npm and bower to build the actual plugin. I will release 2.0.2 tomorrow or the day after.
