### ISSUE TITLE
Most recent update of BWP-recaptcha causes my site to crash with an HTTP error 500

### ISSUE THREAD

**Issue by WoodcraftNinjas** [OddOneOut/bwp-recaptcha#24]
After updating WordPress plugins, my entire site started crashing with an HTTP error 500 on every page, even WordPress admin pages. After disabling plugins and adding them back one by one, I determined that it was BWP-recaptcha that was the cause. When I try to re-enable the plugin, it gives me "Plugin could not be activated because it triggered a fatal error. Parse error: syntax error, unexpected T_FUNCTION in /home1/woodcrb2/public_html/wp-content/plugins/bwp-recaptcha/bwp-recaptcha.php on line 51".

There have been no edits to that PHP file, nor any of the other files that are directly part of that plugin. I've even tried deleting and reinstalling the plugin, and I get the same result trying to activate it. Any ideas?

**Comment by kminh** [comment]
It seems like you are using PHP 5.2, can you check your PHP version ? There's a beta version that should fix this issue, you can download it here: https://downloads.wordpress.org/plugin/bwp-recaptcha.zip

**Comment by kminh** [comment]
ping @WoodcraftNinjas

**Comment by kminh** [comment]
Should be fixed by commit 12b726da9437e19c2db7589b77784294948abebb

The fix will be included in 2.0.2, if you still see the error please reopen this ticket.
